version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: graphdone_dev
      POSTGRES_USER: graphdone
      POSTGRES_PASSWORD: graphdone_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graphdone"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server-dev:
    build:
      context: .
      dockerfile: packages/server/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://graphdone:graphdone_password@postgres:5432/graphdone_dev
      - PORT=4000
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/server/node_modules
    command: npm run dev

  web-dev:
    build:
      context: .
      dockerfile: packages/web/Dockerfile.dev
    environment:
      - VITE_GRAPHQL_URL=http://localhost:4000/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:4000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - server-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/web/node_modules
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data: