version: '3.8'

services:
  graphdone-neo4j:
    container_name: graphdone-neo4j
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/graphdone_password
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - graphdone_neo4j_data:/data
      - graphdone_neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "graphdone_password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphdone-redis:
    container_name: graphdone-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - graphdone_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphdone-api:
    container_name: graphdone-api
    build:
      context: ..
      dockerfile: packages/server/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://graphdone-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphdone_password
      - PORT=4127
      - CORS_ORIGIN=http://localhost:3127
    ports:
      - "4127:4127"
    depends_on:
      graphdone-neo4j:
        condition: service_healthy
      graphdone-redis:
        condition: service_healthy

  graphdone-web:
    container_name: graphdone-web
    build:
      context: ..
      dockerfile: packages/web/Dockerfile.dev
    environment:
      - VITE_GRAPHQL_URL=http://localhost:4127/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:4127/graphql
      - PORT=3127
    ports:
      - "3127:3127"
    depends_on:
      - graphdone-api

volumes:
  graphdone_neo4j_data:
  graphdone_neo4j_logs:
  graphdone_redis_data: