services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/graphdone_password
      NEO4J_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "graphdone_password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ..
      dockerfile: packages/server/Dockerfile
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphdone_password
      - PORT=4127
      - CORS_ORIGIN=http://localhost:3127
    ports:
      - "4127:4127"
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../packages/server/.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4127/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ..
      dockerfile: packages/web/Dockerfile
    environment:
      - VITE_GRAPHQL_URL=http://localhost:4127/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:4127/graphql
    ports:
      - "3127:3127"
    depends_on:
      - server
    volumes:
      - ../packages/web/.env:/app/.env

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data: